name: Generate Audit Report
on:
  schedule: 
  - cron: '0 3 * * *' # Every day at 3 AM UTC 
permissions:
  contents: write
jobs:
  generate-and-push-audit-report:
    runs-on: uhg-runner-m
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: DDIQA2024
      - name: Set up Git user
        run: |
          git config --global user.email "neha_jain@optum.com"      
          git config --global user.name "Neha Jain"
      - name: Generate commit audit report
        run: |
          echo "Reading last processed commit..."
          if [ -f git-commit-version-MALTSSPROD.txt ]; then
            value=$(<git-commit-version-MALTSSPROD.txt)
            if ! git cat-file -e "$value"; then
              echo "Invalid or missing commit. Falling back to root."
              value=$(git rev-list --max-parents=0 HEAD)
            fi
          else
            echo "No previous commit file found, using root commit"
            value=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "Last commit ID: $value"
          mkdir -p temp
          echo "COMMIT ID,MEMBER EMAIL,DATETIME (IST),COMMENTS,NUMBER OF FILES,NUMBER OF ADDITIONS,NUMBER OF DELETIONS" > temp/AuditReport1.csv
          git log --since="24 hours ago" --pretty=format:'"%H","%ae","%aD","%s",' --shortstat --no-merges | paste - - - >> temp/AuditReport1.csv
          echo "FILES" >temp/AuditReport2.csv
          git log --since="24 hours ago" --name-only --pretty=format:"" > temp/AuditReport3.csv
          awk 'NF {TMP=TMP $0; next} {print TMP " "; TMP=" "} END {print TMP " "}' temp/AuditReport3.csv > temp/AuditReport4.csv
          sed -r '/^\s*$/d' temp/AuditReport4.csv > temp/AuditReport5.csv
          paste temp/AuditReport5.csv >> temp/AuditReport2.csv
          paste -d , temp/AuditReport1.csv temp/AuditReport2.csv > temp/AuditReport.csv
          reportValue=$(<temp/AuditReport.csv)          
          echo "$reportValue" > AuditReport_$(date +'%Y-%m-%d').csv
          attachfile="AuditReport_$(date +'%Y-%m-%d').csv"
      - name: Send Email with Attachment
        if: always()
        uses: uhg-pipelines/epl-send-mail@v1
        with:
          subject: "Automation Run Completed for ::  ${{github.workflow}}"
          to: neha_jain@optum.com
          from: notifications@github.com
          attachments: | 
            AuditReport_$(date +'%Y-%m-%d').csv
          body: |
            Hello Neha,
              PFA audit report
            Regards
            GitHub Actions 
      - name: Commit and push report to DDIQA2024
        run: |
          lastcommitid=$(git log -1 --pretty=format:"%H")
          echo "$lastcommitid" > git-commit-version-MALTSSPROD.txt
          echo "Workflow name is: ${{github.workflow}}"
          #git add temp 
          git add git-commit-version-MALTSSPROD.txt AuditReport_$(date +'%Y-%m-%d').csv
          git commit -m "Auto-generated audit report"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:DDIQA2024
